version: '3.7'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: mijn
      MYSQL_PASSWORD: eenheelerglangenlastigteradenwachtwoord
      MYSQL_DATABASE: movie-meter-db
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - '3313:3306'